cownet:
  enable: true

starve:
  enable: true
  radius: 5
  damage: 20

bounce:
  enable: true
  velocity: 1
  radius: 5

noswearing:
  enable: true
  fireTicks: 5
  mobsToSpawn: 5
  launchVelocity: 2
  lightningDamage: 3
  bannedPhrases: badwords.txt

tntsheep:
  enable: true
  chanceToExplode: 25
  explosionRadius: 3
  explosionDamage: 3
  sheepExplode: true
  cowsExplode: true
  wreckage: 5
  allowedWords: ALL

logins:
  enable: true
  savegamemode: true

FlingPortal:
  enable: true

plot:
  enable: true
  maxPlots: 4
  plotSize: 64
  plotHeight: 20
  plotBase: STONE
  plotSurface: GRASS
  plotPath: DOUBLE_STEP
  plotCost: 100

rank:
  enable: true
  groupNames: Convict,BadBoy,Default,Builder,Trusted,Engineer,BossBuilder,Architect,EarthMover,Terraformer,BlockGod

timber:
  enable: true;
  worlds: ALL

hardcore:
  enable: true
  debug: false
  worldname: HardCore
  safedistance: 50
  livetimeout: 518400
  deathDuration: 60
  timeoutgrowth: 2.0
  difficulty: HARD
  monsterBoost: 1.0
  allowFly: false
  allowXRay: false

hungergames:
  enable: true
  debug: false
  worldName: HungerGames
  arenaSize: 100
  allowFly: false
  allowXRay: false
  minTributes: 2
  giftsPerPlayer: 3
  trapsPerPlayer: 3
  timeToGather: 60000
  timeToAcclimate: 10000

hide:
  enable: true
  debug: false

snapshot:
  enable: true
  debug: false

jail:
  enable: true
  debug: false

cowperms:
  enable: true
  debug: false

cowrank:
  enable: true
  debug: false
  groupNames: Convict,BadBoy,Default,Builder,Trusted,Engineer,BossBuilder,Architect,EarthMover,Terraformer,BlockGod

cowwarp:
  enable: true
  debug: false

