name: CowNetPlugin
main: us.fitzpatricksr.cownet.CowNetMod
author: minecraft@fitzpatricksr.us
version: $Id:$
load: startup
softdepend: [Multiverse-Core, WorldGuard, WorldEdit, BOSEconomy]
commands:
  starve:
      description: Starve mobs and players around you
      usage: Use "/starve help? for help.
  bounce:
      description: Bounce mobs and players around you
      usage: Use "/bounce help" for help.
  tntsheep:
      description: Some sheep go boom!
      usage: tntsheep
  logins:
      description: show who has logged in recently
      usage: Use "/logins help" for help.
  flingportal:
      description: place a redstone torch under a glass block and step on the block.
      usage: flingportal
  plot:
      description: claim a plot of land for building
      usage: Use "/plot help" for help.
  hide:
      description: hide from other players.  Sshhhh....
      usage: Use "/hide help" for help
  rank:
      description: promote/demote a player
      usage: Use "/rank help"
  timber:
      description: Yeah.  It's about trees
      usage: Use "/timber help"
  hardcore:
      aliases: [ hc ]
      description: Go to the Hard Core world.
      usage: Use "/hardcore help"
  hungergames:
      aliases: [ games ]
      description: Enter the games
      usage: Use "/hungergames help"
  nickname:
      description: nicknames duh?
      usage: Use "/nickname help"
  noswearing:
      description: Keep it clean.  This is a family show.
      usage: Nice, clean words.
  snapshot:
      aliass: [ snap ]
      description: Keepin the streets safe
      usage: Use /snapshot help.

permissions:
    cownet.starve:
        description: Starve creatures around you
        default: true
    cownet.bounce:
        description: Bounce creatures around you
        default: true
    cownet.noswearing.allowed:
        description: You are allowed to use bad words
        default: false      
    cownet.tntsheep:
        description: are you allowed to call apon the sheep
        default: true
    cownet.tntsheep.immune:
        description: are you immune to the sheep
        default: false
    cownet.flingportal:
        description: do you fling?
        default: true
    cownet.plot:
        description: can  use plots in general
        default: true
    cownet.plot.claim:
        description: are you allowed to claim land
        default: true
    cownet.plot.unlimitedplots:
        description: if true the player is allowed unlimited active plots
        default: op
    cownet.hide:
        description: if true player has permission to hide
        default: op
    cownet.hide.joinHidden:
        description: if true player joins the game hidden
        default: false
    cownet.hide.seesInvisible:
        description: if true player can see invisible players (srsly)
        default: false
    cownet.rank:
        description: If true, allows access to the rankup command
        default: op
    cownet.timber:
        description: If true, allows access to the timber command
        default: true
    cownet.hardcore:
        description: If true, allows access to the HardCore command
        default: true
    cownet.hardcore.info:
        description: Do you know HARD CORE when you see it?
        default: true
    cownet.hardcore.regen:
        description: Can you regenerate the HARD CORE world?
        default: op
    cownet.hardcore.revive:
        description: Can you give wimps another chance to be HARD CORE?
        default: op
    cownet.hardcore.keepop:
        description: do you stay op in hardcore
        default: false
    cownet.hardcore.canAlwaysEscape:
        description: can you hc out from anywhere
        default: op
    cownet.hungergames:
        description: participate in Hunger Games
        default: true
    cownet.hungergames.gamemaker:
        description: can you visit the arena even if games aren't underway
        default: false
    cownet.snapshot.jail:
        description: send someone to jail
        default: op
    cownet.snapshot.release:
        description: set someone free
        default: op
    cownet.snapshot.snapshot:
        description: create a new jail snapshot from jail region and save it
        default: op
    cownet.snapshot.reset:
        description: restore jail from the last snapshot
        default: op


