name: CowNetPlugin
main: us.fitzpatricksr.cownet.CowNetMod
version: 1.0.0
load: startup
commands:
  starve:
      description: Starve mobs and players around you
      usage: Use "/starve help? for help.
  bounce:
      description: Bounce mobs and players around you
      usage: Use "/bounce help" for help.
  tntsheep:
      description: Some sheep go boom!
      usage: tntsheep
  logins:
      description: show who has logged in recently
      usage: Use "/logins help" for help.
  flingportal:
      description: place a redstone torch under a glass block and step on the block.
      usage: flingportal
  plot:
      description: claim a plot of land for building
      usage: Use "/plot help" for help.
permissions:
    cownet.starve:
        description: Starve creatures around you
        default: true
    cownet.bounce:
        description: Bounce creatures around you
        default: true
    cownet.noswearing.allowed:
        description: You are allowed to use bad words
        default: false      
    cownet.tntsheep:
        description: are you allowed to call apon the sheep
        default: true
    cownet.tntsheep.immune:
        description: are you immune to the sheep
        default: false
    cownet.flingportal:
        description: do you fling?
        default: true
    cownet.plot:
        description: can use plots in general
        default: true
    cownet.plot.claim:
        description: are you allowed to claim land
        default: true
    cownet.plot.unlimitedplots:
        description: if true the player is allowed unlimited active plots
        default: false